name: Check Package Version and README Update

on:
  pull_request:
    branches:
      - main

jobs:
  version-and-readme-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Get version from PR branch
        id: pr_version
        run: echo "::set-output name=VERSION::$(node -p \"require('./package.json').version\")"

      - name: Check README.md in PR branch
        id: pr_readme
        run: |
          if git diff --name-only ${{ github.base_ref }} | grep -q 'README.md'; then
            echo "::set-output name=UPDATED::true"
          else
            echo "::set-output name=UPDATED::false"
          fi

      - name: Check out main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Get version from main branch
        id: main_version
        run: echo "::set-output name=VERSION::$(node -p \"require('./package.json').version\")"

      - name: Compare versions and check README.md
        run: |
          PR_VERSION=${{ steps.pr_version.outputs.VERSION }}
          MAIN_VERSION=${{ steps.main_version.outputs.VERSION }}
          README_UPDATED=${{ steps.pr_readme.outputs.UPDATED }}
          
          if [ "$PR_VERSION" = "$MAIN_VERSION" ]; then
            echo "Version in package.json ($PR_VERSION) has not been incremented from the main branch version ($MAIN_VERSION)"
            exit 1
          fi

          if [ "$README_UPDATED" = "false" ]; then
            echo "README.md has not been updated."
            exit 1
          fi

          echo "Checks passed. PR version: $PR_VERSION, Main branch version: $MAIN_VERSION, README updated: $README_UPDATED"
